cc_test(
  name = "Client",
  size = "small",
  srcs = ["ClientTests.cpp"],
  deps = [
    "@com_google_googletest//:gtest_main",
    "//Client:Client",
    "//Testing/Mocks:Mocks"
  ],
)

cc_test(
  name = "Communication",
  size = "small",
  srcs = ["CommunicationTests.cpp"],
  deps = [
    "@com_google_googletest//:gtest_main",
    "//Communication:Communication",
  ],
)

cc_test(
  name = "Logger",
  size = "small",
  srcs = ["LoggerTests.cpp"],
  deps = [
    "@com_google_googletest//:gtest_main",
    "//Logger:Logger",
  ],
)

cc_test(
  name = "Server",
  size = "small",
  srcs = ["ServerTests.cpp"],
  deps = [
    "@com_google_googletest//:gtest_main",
    "//Server:Server",
  ],
)

cc_test(
  name = "Tamagotchi",
  size = "small",
  srcs = ["TamagotchiTests.cpp"],
  deps = [
    "@com_google_googletest//:gtest_main",
    "//Tamagotchi:Tamagotchi",
  ],
)