cc_test(
  name = "ClientTests",
  size = "small",
  srcs = ["ClientTests.cpp"],
  deps = [
    "@com_google_googletest//:gtest_main",
    "//Client:Client",
  ],
)

cc_test(
  name = "CommunicationTests",
  size = "small",
  srcs = ["CommunicationTests.cpp"],
  deps = [
    "@com_google_googletest//:gtest_main",
    "//Communication:Communication",
  ],
)

cc_test(
  name = "LoggerTests",
  size = "small",
  srcs = ["LoggerTests.cpp"],
  deps = [
    "@com_google_googletest//:gtest_main",
    "//Logger:Logger",
  ],
)

cc_test(
  name = "ServerTests",
  size = "small",
  srcs = ["ServerTests.cpp"],
  deps = [
    "@com_google_googletest//:gtest_main",
    "//Server:Server",
  ],
)

cc_test(
  name = "Tamagotchi",
  size = "small",
  srcs = ["TamagotchiTests.cpp"],
  deps = [
    "@com_google_googletest//:gtest_main",
    "//Tamagotchi:Tamagotchi",
  ],
)